### PR TITLE
Feature/from density; Add from_density method (generalised from from_pressure)

### PR DESCRIPTION
**Pull request by sylvainvandermeer**
Add ability to convert a density to an atmosphere instance, analogous to the from_pressure method

### CODE REVIEW

**Comment by aarondettmann** [comment]
Dear Sylvain, thank you for your suggestion to add a `from_density()` method. In general I think it might be fine to include it. However, before doing so a few comments.

What is the use case to have a `from_density()` method? I assume you have needed it for something.

Personally, I would prefer to simply have the `from_density()` implemented analogous to `from_pressure`. There is no need to create a `__from_()` which at first glance looks more general, but then contains the special cases `variable == 'pressure'` and `variable == 'density'`. But that is just my opinion. I also think it is unlikely that it would be of interest to implement other similar methods, like `from_kinematic_viscosity()`. At least for now I cannot see the use case.

**Comment by sylvainvandermeer** [comment]
Hi Aaron, cheers for the valuable comments. The use case is for density altitude, as in most aircraft manuals density altitude is used. Hence, when evaluating an aircraft at some density, the representative density altitude must be found.

With respect to the implementation I suspect that this is just a matter of preference. With an analogous implementation to `from_pressure`, one cannot avoid large chunks of copied code. I personally prefer to have a general method that initialises specific variables in a clear place at the beginning of the method instead of copied code. If that's considered bad practice, please do feel free to point that out :) . I do agree that it is unlikely that other similar methods would arise, however if one would arise implementation would be straightforward.

**Comment by aarondettmann** [comment]
Thanks! I had not heard of the concept of "density altitude" before.

I am happy to add the `from_density()` method. If it's fine for you too, I be slighty more happy to just make the new method a simple copy of `from_pressure()`. It's a very short method, and we don't have to repeat the comments, I think. So just something like this maybe:

```python
@classmethod
def from_density(cls, rho):
    """Return a new instance for given density value(s)"""

    rho = cls._make_tensor(rho)
    if (rho < CONST.rho_min-_EPS).any() or (rho > CONST.rho_max+_EPS).any():
        raise ValueError(
            "Value out of bounds." +
            f" Lower limit: {CONST.rho_min:.1e} kg/m^3." +  # TODO: Test which number formatting looks good...
            f" Upper limit: {CONST.rho_max:.2f} kg/m^3."
        )

    def f(ht):
        return np.log10(p/cls(ht, check_bounds=False).density)

    return cls(h=opt.newton(f, x0=...))
```

I'd prefer this in favor of readability than having to assemble with `getattr()`. As said before, I don't believe other `from_*()` methods would be of interest (also since some properties, like temperature, can have multiple solutions), but if they are we can revisit some generalizations.

I am not sure I will manage to package this new addition today or during the weekend for PyPI, but latest beginning of next week :)

**Comment by aarondettmann** [comment]
@sylvainvandermeer -- The updated package (version 1.3.0) is now on [PyPI](https://pypi.org/project/ambiance/). Thank you for adding this feature :slightly_smiling_face:

**Pull request merged**
